project:
  type: website

website:
  title: "Bioinformatics Basics"
  site-url: "https://gladkia.github.io/bioinformatics-basics/"
  
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
    right:
      - text: "🌐 Język / Language"
        menu:
          - text: "🇵🇱 Polski"
            href: index.qmd
          - text: "🇬🇧 English"
            href: en/index.qmd
      - icon: github
        href: "https://github.com/gladkia/bioinformatics-basics"
        aria-label: "Kod źródłowy na GitHub"
        
  sidebar:
    - id: pl-sidebar
      title: "Podstawy Bioinformatyki"
      style: "docked"
      search: true
      contents:
        - section: "Informacje organizacyjne"
          contents:
            - text: "Sylabus i zaliczenie"
              file: index.qmd
        - section: "Wykłady"
          contents:
            - text: "Wykład 1: Wstęp"
              file: wyklad_1.qmd
            - text: "Wykład 2: Bioinformatyka strukturalna"
              file: wyklad_2.qmd
        - section: "Materiały ćwiczeniowe"
          contents:
            - text: "Lab 1: Bazy danych i API"
              file: laboratorium_1.qmd
            - text: "Lab 2: Algorytmy przyrównań"
              file: laboratorium_2.qmd
            - text: "Lab 3: Profile i Ewolucja"
              file: laboratorium_3.qmd
            - text: "Lab 4: Analiza danych NGS"
              file: laboratorium_4.qmd
            - text: "Lab 5: Struktury białek (AI)"
              file: laboratorium_5.qmd
            - text: "Lab 6: RNA-Seq (Ekspresja)"
              file: laboratorium_6.qmd
            - text: "Lab 7: Dokowanie leków"
              file: laboratorium_7.qmd
        - section: "Ważne linki"
          contents:
            - text: "Wyniki (Google Docs)"
              href: "https://docs.google.com/spreadsheets/d/134NhK2FivqKk_JKwuKuD5fQUU7I2K1My4uIS0cXf9D4/edit?gid=1783411386#gid=1783411386"
            - text: "Wykłady (Google Drive)"
              href: "https://drive.google.com/drive/u/1/folders/1_b4-G2htQCMede0pPzfo7Arm2nV-s874"
            - text: "Test zaliczeniowy (Moodle)"
              href: "https://moodle.dobio.link/mod/quiz/view.php?id=3"

    - id: en-sidebar
      title: "Bioinformatics Basics"
      style: "docked"
      search: true
      contents:
        - section: "Course Information"
          contents:
            - text: "Syllabus & Grading"
              file: en/index.qmd
        - section: "Lectures"
          contents:
            - text: "Lecture 1: Intro"
              file: en/lecture_1.qmd
            - text: "Lecture 2: Structures"
              file: en/lecture_2.qmd
        - section: "Laboratory Classes"
          contents:
            - text: "Lab 1: Databases & APIs"
              file: en/lab_1.qmd
            - text: "Lab 2: Sequence Alignment"
              file: en/lab_2.qmd
            - text: "Lab 3: Profiles & Evolution"
              file: en/lab_3.qmd
            - text: "Lab 4: Intro to NGS"
              file: en/lab_4.qmd
            - text: "Lab 5: Protein Structures (AI)"
              file: en/lab_5.qmd
        - section: "Important Links"
          contents:
            - text: "Grades (Google Docs)"
              href: "https://docs.google.com/spreadsheets/d/134NhK2FivqKk_JKwuKuD5fQUU7I2K1My4uIS0cXf9D4/edit?gid=1783411386#gid=1783411386"
            - text: "Lectures (Google Drive)"
              href: "https://drive.google.com/drive/u/1/folders/1_b4-G2htQCMede0pPzfo7Arm2nV-s874"

format:
  html:
    embed-resources: true
    theme: 
      light: flatly
      dark: darkly
    toc: true
    toc-title: "Content"
    toc-depth: 3
    smooth-scroll: true
